sut:
    build: .
    dockerfile: Dockerfile.test
    environment:
        - TASK_SERVICE_URL=http://taskservice:9000
    links:
        - taskservice

taskservice:
    build: .
    command: /go/bin/taskservice
    dockerfile: Dockerfile
    links:
        - db
    ports:
        - 80:8080
    volumes:
        - $GOPATH/src/github.com/bsedg/slacker:/go/src/github.com/bsedg/tasker
    working_dir: /go/src/github.com/bsedg/tasker
    environment:
        - AUTH_KEY=U1RGVzMzQUc0TlZXMDIzRkwxCg
        - PORT=:8080
        - MYSQL_DATABASE=tasker
        - MYSQL_USER=taskerservice
        - MYSQL_PASSWORD=somepassword
        - MYSQL_HOST=db
        - MYSQL_PORT=3306
        - VERSION_FILE=/version

db:
    image: mysql:latest
    ports:
        - 3306
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=tasker
        - MYSQL_USER=taskerservice
        - MYSQL_PASSWORD=somepassword
